.\" $Id$
.TH IROFFER 1 "Januar 2011" "All Posix OS" "User Manuals"
.SH NAME
iroffer \-\- DCC file server bot
.SH SYNOPSIS
.TP
.B iroffer -v
.TP
.B iroffer -c [configfile]
.TP
.B iroffer [-b] [-d] [-k] [-n] [-s] [-u user] [-t dir] [-i file] configfile [configfile ...]
.SH DESCRIPTION
.B iroffer
is a file server which uses the DCC feature of IRC to send requested
files to other users. The name of a configuration file must be given
on the command line for normal operation.
.SH OPTIONS
.TP
.B \-v
Display version information and exit.
.TP
.B \-c
Generate an encrypted password and exit.
If a configfile is given, the encrypted password will not be printed, but directly added to the end of the configfile.
.TP
.B \-b
Run in the background.
.TP
.B \-d
Increase debug level.
.TP
.B \-k
Attempt to adjust ulimit to allow core files.
.TP
.B \-n
No colors in foreground mode.
.TP
.B \-s
No screen manipulation in foreground mode.
.TP
.B \-u user
Run as user (you have to start as root).
.TP
.B \-t dir
Chroot to dir (you have to start as root).
.TP
.B \-w dir
Chdir to dir as working directory.
.TP
.B \-i file
Import and old style mybot.xdcc file.
.SH "IMPLEMENTATION NOTES"
.TP
.B multiple IRC networks
Supports connecting to multiple IRC networks at the same time.
.TP
.B IPv6
Supports connecting and transfers via IPv6
.TP
.B DCC
Supports transfers of files greater 4 GB.
.TP
.B passive DCC
Supports passive DCC transfers and uploads.
.TP
.B HTTP server
Supports internal HTTP server for status and pack list.
.TP
.B Telnet server
Supports internal Telnet server for background administration.
.TP
.B FISH encrpytion
Support for FISH encryption for mesasages and channel.
.TP
.B SSL encrpytion
Optional support to connect via SSL to IRC-servers if OpenSSL or GnuTLS is availible.
.TP
.B CertFP with SSL
CertFP Authentification with SSL.
.TP
.B GeoIP and GeoIPv6
Optional support to limit transfers to countrys with libGeoIP.
.TP
.B Curl
Optional support to fetch files via FTP/HTTP if libcurl is compiled in.
.TP
.B UPnP
Optional Universal Plug and Play support to connect via NAT Routers, this requires lib miniupnpc present.
Used to obtain public IP-Address and Set/Remove port forwardings for incomming connections.
.TP
.B Ruby
Optional support for scripting plugins in Ruby.
Support for CGI scripts with the internal HTTP server.
.TP
.B XML
Support for XML Packlist allows integration with other websites.
.TP
.B Batch
Allows batched transfers without delaying new users.
.SH RETURN VALUES
The iroffer program exits 0 on successful termination, and >0 if an error occurs.
.SH "SIGNALS"
.TP
.B SIGUSR1
Jumps to another server, same as admin command "JUMP".
.IP
kill \-USR1 `mybot.pid`
.TP 
.B SIGUSR2
Re-reads config file, same as admin command "REHASH"
.IP
kill \-USR2 `mybot.pid`
.TP 
.B SIGTERM
Shuts down iroffer, same as admin command "SHUTDOWN NOW"
.IP
kill `mybot.pid`
.SH "FILES"
.TP
.B mybot.pid
the pid of the currently running iroffer
.TP
.B mybot.state
the main database for the iroffer
.TP
.B mybot.txt
generated list of packs in plain text
.TP
.B mybot.xml
generated list of packs in XML
.TP
.B mybot.log
logfile wit all notes error and while running
.SH "SEE ALSO"
.TP
.B /usr/share/doc/iroffer
Please look for more detailed information in this directory.
.TP
.B http://iroffer.dinoex.net/
Downloads and Documentation.
.TP
.B http://iroffer.dinoex.de/projects/show/iroffer
Projectpage with Tracker and RSS feed.
.SH "HISTORY"
The original iroffer version was written by by David Johnson.
.TP
iroffer-dinoex is developed by Dirk Meyer.
