#!/bin/sh
lang="${1-de}"
if test "${lang}" = "en"
then
	for c in src/iroffer*.c src/dinoex*.c
	do
		if test -f "${c}.en"
		then
			echo \
			mv -f "${c}.en" "${c}"
			mv -f "${c}.en" "${c}"
		fi
	done
	exit 0
fi
echo -n "parsing ... "
grep -v "^#" "${lang}.txt" |
while read nr text
do
	if ! grep -q "^${nr} " en.txt
	then
		continue
	fi
	en=`grep "^${nr} " "en.txt"`
	en="${en#* }"
	text=`grep "^${nr} " "${lang}.txt"`
	text="${text#* }"
	if test "${en}" = "${text}"
	then
		continue
	fi
	echo "s°${en}°${text}°"
done |
sed -e 's|\\|\\\\|g' -e 's|\*|\\*|g' -e 's|\+|\\+|g' -e 's|\.|\\.|g' -e 's|\[|\\[|g' -e 's|\]|\\]|g' > "${lang}.sed"
echo "done"
for c in src/iroffer*.c src/dinoex*.c
do
	if test ! -f "${c}.en"
	then
		echo \
		cp -p "${c}" "${c}.en"
		cp -p "${c}" "${c}.en"
	fi
	sed -f "${lang}.sed" "${c}".en > "${c}.new"
	if diff -q "${c}" "${c}.new"
	then
		rm -f "${c}.new"
		continue
	fi
	echo \
	mv -f "${c}.new" "${c}"
	mv -f "${c}.new" "${c}"
done
# eof
