# @(#) Makefile.config 1.82@(#)
# pmg@wellington.i202.centerclick.org|Makefile.config|20051123201124|64724

NAME      = iroffer$(VERSION)
INSDIR    = /usr/local/bin

IROFFER_OBJECTS = \
	obj/iroffer_admin.o \
	obj/iroffer_dccchat.o \
	obj/iroffer_display.o \
	obj/iroffer_main.o \
	obj/plumb_md5.o \
	obj/iroffer_misc.o \
	obj/iroffer_statefile.o \
	obj/iroffer_transfer.o \
	obj/iroffer_upload.o \
	obj/dinoex_admin.o \
	obj/dinoex_main.o \
	obj/dinoex_misc.o \
	obj/dinoex_http.o \
	obj/dinoex_upload.o \
	obj/dinoex_transfer.o \
	obj/dinoex_geoip.o \
	obj/dinoex_ssl.o \
	obj/dinoex_curl.o \
	obj/dinoex_irc.o \
	obj/dinoex_queue.o \
	obj/dinoex_telnet.o \
	obj/dinoex_badip.o \
	obj/dinoex_jobs.o \
	obj/dinoex_ruby.o \
	obj/dinoex_config.o \
	obj/crc32.o \
	obj/upnp.o \
	obj/blowfish.o \
	obj/iroffer_utilities.o \
	obj/dinoex_utilities.o

HEADERS   = \
	src/iroffer_config.h \
	src/iroffer_defines.h \
	src/iroffer_globals.h \
	src/iroffer_headers.h \
	src/dinoex_admin.h \
	src/dinoex_config.h \
	src/dinoex_curl.h \
	src/dinoex_geoip.h \
	src/dinoex_globals.h \
	src/dinoex_badip.h \
	src/dinoex_http.h \
	src/dinoex_irc.h \
	src/dinoex_jobs.h \
	src/dinoex_main.h \
	src/dinoex_misc.h \
	src/dinoex_queue.h \
	src/dinoex_ruby.h \
	src/dinoex_ssl.h \
	src/dinoex_telnet.h \
	src/dinoex_transfer.h \
	src/dinoex_upload.h \
	src/dinoex_utilities.h \
	src/plumb_md5.h \
	src/upnp.h \
	src/blowfish.h \
	Makefile

TARED_BASE = \
	$(NAME)/sample.config \
	$(NAME)/beispiel.config \
	$(NAME)/help-admin-en.txt \
	$(NAME)/help-admin-de.txt \
	$(NAME)/README-iroffer.txt \
	$(NAME)/README.modDinoex \
	$(NAME)/LIESMICH.modDinoex \
	$(NAME)/LICENSE \
	$(NAME)/THANKS \
	$(NAME)/TODO

TARED_SRC = \
	$(NAME)/src/iroffer_*.c \
	$(NAME)/src/iroffer_defines.h \
	$(NAME)/src/iroffer_globals.h \
	$(NAME)/src/iroffer_headers.h \
	$(NAME)/src/plumb_md5.h \
	$(NAME)/src/plumb_md5.c \
	$(NAME)/src/dinoex_*.h \
	$(NAME)/src/dinoex_*.c \
	$(NAME)/src/crc32.c \
	$(NAME)/src/upnp.c \
	$(NAME)/src/upnp.h \
	$(NAME)/src/blowfish.h \
	$(NAME)/src/blowfish.c \
	$(NAME)/Makefile.config \
	$(NAME)/Configure \
	$(NAME)/iroffer.cron

OBJDIR = obj/.mkdir

LDLIBS    = $(CONFIG_LDLIBS)
LDFLAGS   = $(CONFIG_LDFLAGS)
CFLAGS    = $(CONFIG_CFLAGS)
CPPFLAGS  = -Isrc $(CONFIG_CPPFLAGS)

all: iroffer$(CONFIG_EXE) $(CONFIG_TARGETS)

iroffer$(CONFIG_EXE): $(OBJDIR) $(IROFFER_OBJECTS)
	$(CC) $(LDFLAGS) $(IROFFER_OBJECTS) $(LOADLIBES) $(LDLIBS) -o iroffer

iroffer_chroot$(CONFIG_EXE): $(OBJDIR) $(IROFFER_OBJECTS)
	$(CC) $(LDFLAGS) $(IROFFER_OBJECTS) $(LOADLIBES) $(LDLIBS) $(CONFIG_CHROOT) -o iroffer_chroot

src-doc:
	mkdir -p srcdocs
	cxref -block-comments -index-all -xref-all -Osrcdocs \
		-Niroffer $(CPPFLAGS) src/*.c src/*.h
	cxref -block-comments -index-all -xref-all -Osrcdocs \
		-Niroffer $(CPPFLAGS) -html20 src/*.c src/*.h

$(OBJDIR):
	mkdir -p obj
	touch $(OBJDIR)

obj/irofferall.o: $(OBJDIR) $(IROFFER_OBJECTS)
	$(LD) -r -o obj/irofferall.o $(IROFFER_OBJECTS)

obj/iroffer_admin.o: src/iroffer_admin.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_admin.o src/iroffer_admin.c
obj/iroffer_dccchat.o: src/iroffer_dccchat.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_dccchat.o src/iroffer_dccchat.c
obj/iroffer_display.o: src/iroffer_display.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_display.o src/iroffer_display.c
obj/iroffer_main.o: src/iroffer_main.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_main.o src/iroffer_main.c
obj/plumb_md5.o: src/plumb_md5.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/plumb_md5.o src/plumb_md5.c
obj/iroffer_misc.o: src/iroffer_misc.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_misc.o src/iroffer_misc.c
obj/iroffer_statefile.o: src/iroffer_statefile.c $(HEADERS) $(OBJDIR) src/dinoex_statefile.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_statefile.o src/iroffer_statefile.c
obj/iroffer_transfer.o: src/iroffer_transfer.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_transfer.o src/iroffer_transfer.c
obj/iroffer_upload.o: src/iroffer_upload.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_upload.o src/iroffer_upload.c
obj/iroffer_utilities.o: src/iroffer_utilities.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_utilities.o src/iroffer_utilities.c

obj/dinoex_config.o: src/dinoex_config.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_config.o src/dinoex_config.c
obj/dinoex_jobs.o: src/dinoex_jobs.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_jobs.o src/dinoex_jobs.c
obj/dinoex_badip.o: src/dinoex_badip.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_badip.o src/dinoex_badip.c
obj/dinoex_telnet.o: src/dinoex_telnet.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_telnet.o src/dinoex_telnet.c
obj/dinoex_queue.o: src/dinoex_queue.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_queue.o src/dinoex_queue.c
obj/dinoex_ruby.o: src/dinoex_ruby.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_ruby.o src/dinoex_ruby.c
obj/dinoex_irc.o: src/dinoex_irc.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_irc.o src/dinoex_irc.c
obj/dinoex_curl.o: src/dinoex_curl.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_curl.o src/dinoex_curl.c
obj/dinoex_ssl.o: src/dinoex_ssl.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_ssl.o src/dinoex_ssl.c
obj/dinoex_geoip.o: src/dinoex_geoip.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_geoip.o src/dinoex_geoip.c
obj/dinoex_upload.o: src/dinoex_upload.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_upload.o src/dinoex_upload.c
obj/dinoex_transfer.o: src/dinoex_transfer.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_transfer.o src/dinoex_transfer.c
obj/dinoex_http.o: src/dinoex_http.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_http.o src/dinoex_http.c
obj/dinoex_main.o: src/dinoex_main.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_main.o src/dinoex_main.c
obj/dinoex_misc.o: src/dinoex_misc.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_misc.o src/dinoex_misc.c
obj/dinoex_admin.o: src/dinoex_admin.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_admin.o src/dinoex_admin.c
obj/dinoex_utilities.o: src/dinoex_utilities.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/dinoex_utilities.o src/dinoex_utilities.c
obj/crc32.o: src/crc32.c $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/crc32.o src/crc32.c
obj/upnp.o: src/upnp.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/upnp.o src/upnp.c
obj/blowfish.o: src/blowfish.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/blowfish.o src/blowfish.c


tar: clean
	cd .. && tar -cf $(NAME)/$(NAME).tar $(TARED_BASE) $(TARED_SRC)
	gzip -9 $(NAME).tar

winbin: clean iroffer$(CONFIG_EXE)
	cd .. && zip -q $(NAME)/iroffer_win32bin_$(VERSION).zip $(TARED_BASE) $(NAME)/iroffer$(CONFIG_EXE) $(NAME)/cygwin1.dll $(NAME)/cygcrypt-0.dll

clean:
	rm -rf iroffer iroffer.exe iroffer_chroot iroffer_chroot.exe core obj src/*~ *~

install: all
	install -o root -g $(INSTALL_GROUP) -m 0755 iroffer$(CONFIG_EXE) $(INSDIR)/iroffer$(CONFIG_EXE)

installuser: all
	install -m 0755 iroffer$(CONFIG_EXE) $(INSDIR)/iroffer$(CONFIG_EXE)

# end
