# @(#) Makefile.config 1.81@(#)
# pmg@wellington.i202.centerclick.org|Makefile.config|20040405004244|54291

NAME      = iroffer$(VERSION)
INSDIR    = /usr/local/bin

IROFFER_OBJECTS = \
	obj/iroffer_admin.o \
	obj/iroffer_dccchat.o \
	obj/iroffer_display.o \
	obj/iroffer_main.o \
	obj/iroffer_md5.o \
	obj/iroffer_misc.o \
	obj/iroffer_statefile.o \
	obj/iroffer_transfer.o \
	obj/iroffer_upload.o \
	obj/iroffer_utilities.o

CONVERTXDCCFILE_OBJECTS = \
	obj/convertxdccfile.o \
	obj/iroffer_md5.o \
	obj/iroffer_statefile.o \
	obj/iroffer_utilities.o

HEADERS   = \
	src/iroffer_config.h \
	src/iroffer_defines.h \
	src/iroffer_globals.h \
	src/iroffer_headers.h \
	src/iroffer_md5.h \
	Makefile

TARED_BASE = \
	$(NAME)/sample.config \
	$(NAME)/README \
	$(NAME)/COPYING \
	$(NAME)/WHATSNEW

TARED_SRC = \
	$(NAME)/src/convertxdccfile.c \
	$(NAME)/src/iroffer_*.c \
	$(NAME)/src/iroffer_defines.h \
	$(NAME)/src/iroffer_globals.h \
	$(NAME)/src/iroffer_headers.h \
	$(NAME)/src/iroffer_md5.h \
	$(NAME)/.cset_number \
	$(NAME)/Makefile.config \
	$(NAME)/Configure \
	$(NAME)/iroffer.cron \
	$(NAME)/dynip.sh

LDLIBS    = $(CONFIG_LDLIBS)
LDFLAGS   = $(CONFIG_LDFLAGS)
CFLAGS    = $(CONFIG_CFLAGS)
CPPFLAGS  = -Isrc $(CONFIG_CPPFLAGS)

all: convertxdccfile$(CONFIG_EXE) iroffer$(CONFIG_EXE) $(CONFIG_TARGETS)

convertxdccfile$(CONFIG_EXE): obj $(CONVERTXDCCFILE_OBJECTS)
	$(CC) $(LDFLAGS) $(CONVERTXDCCFILE_OBJECTS) $(LOADLIBES) $(LDLIBS) -o convertxdccfile

iroffer$(CONFIG_EXE): obj $(IROFFER_OBJECTS)
	$(CC) $(LDFLAGS) $(IROFFER_OBJECTS) $(LOADLIBES) $(LDLIBS) -o iroffer

iroffer_chroot$(CONFIG_EXE): obj $(IROFFER_OBJECTS)
	$(CC) $(LDFLAGS) $(IROFFER_OBJECTS) $(LOADLIBES) $(LDLIBS) $(CONFIG_CHROOT) -o iroffer_chroot

src-doc:
	mkdir -p srcdocs
	cxref -block-comments -index-all -xref-all -Osrcdocs \
		-Niroffer $(CPPFLAGS) src/*.c src/*.h
	cxref -block-comments -index-all -xref-all -Osrcdocs \
		-Niroffer $(CPPFLAGS) -html20 src/*.c src/*.h

obj:
	mkdir -p obj

obj/irofferall.o: obj $(IROFFER_OBJECTS)
	$(LD) -r -o obj/irofferall.o $(IROFFER_OBJECTS)

obj/iroffer_admin.o: src/iroffer_admin.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_admin.o src/iroffer_admin.c
obj/iroffer_dccchat.o: src/iroffer_dccchat.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_dccchat.o src/iroffer_dccchat.c
obj/iroffer_display.o: src/iroffer_display.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_display.o src/iroffer_display.c
obj/iroffer_main.o: src/iroffer_main.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_main.o src/iroffer_main.c
obj/iroffer_md5.o: src/iroffer_md5.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_md5.o src/iroffer_md5.c
obj/iroffer_misc.o: src/iroffer_misc.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_misc.o src/iroffer_misc.c
obj/iroffer_statefile.o: src/iroffer_statefile.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_statefile.o src/iroffer_statefile.c
obj/iroffer_transfer.o: src/iroffer_transfer.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_transfer.o src/iroffer_transfer.c
obj/iroffer_upload.o: src/iroffer_upload.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_upload.o src/iroffer_upload.c
obj/iroffer_utilities.o: src/iroffer_utilities.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_utilities.o src/iroffer_utilities.c

obj/convertxdccfile.o: src/convertxdccfile.c $(HEADERS)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/convertxdccfile.o src/convertxdccfile.c

tar: clean
	touch * src/*
	cd ..; tar -cf $(NAME)/$(NAME).tar $(TARED_BASE) $(TARED_SRC)
	gzip $(NAME).tar
	mv $(NAME).tar.gz $(NAME).tgz

winbin: clean convertxdccfile$(CONFIG_EXE) iroffer$(CONFIG_EXE)
	touch * src/*
	cd ..; zip -q $(NAME)/iroffer_win32bin_$(VERSION).zip $(TARED_BASE) $(NAME)/convertxdccfile$(CONFIG_EXE) $(NAME)/iroffer$(CONFIG_EXE) $(NAME)/cygwin1.dll $(NAME)/cygcrypt-0.dll

clean:
	rm -f iroffer iroffer.exe iroffer_chroot iroffer_chroot.exe core obj/* src/*~ *~

install: all
	install -o root -g root -m 0755 iroffer$(CONFIG_EXE) $(INSDIR)/iroffer$(CONFIG_EXE)

# end
