
now = Time.now.to_s

puts "; Generated by iroffer-dinoex 3.26 on #{now}\r"
puts ";\r"

require "cgi"

cgi = CGI.new('html4Tr')  # New CGI object

def get_post( cgi, name, fallback = '' )
  val = cgi.params[ name ][0]
  if val.nil?
    return fallback
  end
  return val
end

first = get_post( cgi, 'pack', 1 ).to_i
last = get_post( cgi, 'last', first.to_s ).to_i

bot = IrofferEvent.new

pack = first
while true do
  bytes = bot.info_pack(pack, "bytes" )
  if bytes.nil?
    break
  end
  mtime = bot.info_pack(pack, "mtime" )
  file = bot.info_pack(pack, "file" )
  file.sub!( /^.*\//, '' )
  printf( ";%13u  %s %s\r\n", bytes, mtime, file )
  pack += 1
  if pack > last
    break
  end
end

pack = first
while true do
  file = bot.info_pack(pack, "file" )
  if file.nil?
    break
  end
  file.sub!( /^.*\//, '' )
  crc32 = bot.info_pack(pack, "crc32" )
  printf( "%s %s\r\n", file, crc32 )
  pack += 1
  if pack > last
    break
  end
end

# eof
